dbtcrash:
    ouutputs:
        dev:
            job_execution_timeout: 300
            job_retries: 1
            type: bigquery
            method: service-account
            project: dbtcrash
            dataset: dbtcrash
            threads: 1
            keyfile: dbt_bigquery\dbtcrash.json
            timeout_seconds: 300 
        target: dev